[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
regex = "1.9.0"
=======
regex = "1.9.0"
>>>>>>> 0859bb9 (Initial commit)
